// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rf_accel_traverse_tree_Pipeline_TREE_WALK (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        p_read45,
        p_read46,
        p_read47,
        p_read48,
        p_read49,
        p_read50,
        p_read51,
        p_read52,
        p_read53,
        p_read54,
        p_read55,
        p_read56,
        p_read57,
        p_read58,
        p_read59,
        p_read60,
        p_read61,
        p_read62,
        p_read63,
        p_read64,
        tree_id,
        current_out,
        current_out_ap_vld,
        p_ZL14tree_threshold_0_address0,
        p_ZL14tree_threshold_0_ce0,
        p_ZL14tree_threshold_0_q0,
        p_ZL14tree_threshold_1_address0,
        p_ZL14tree_threshold_1_ce0,
        p_ZL14tree_threshold_1_q0,
        p_ZL14tree_threshold_2_address0,
        p_ZL14tree_threshold_2_ce0,
        p_ZL14tree_threshold_2_q0,
        p_ZL14tree_threshold_3_address0,
        p_ZL14tree_threshold_3_ce0,
        p_ZL14tree_threshold_3_q0,
        p_ZL14tree_threshold_4_address0,
        p_ZL14tree_threshold_4_ce0,
        p_ZL14tree_threshold_4_q0,
        p_ZL14tree_threshold_5_address0,
        p_ZL14tree_threshold_5_ce0,
        p_ZL14tree_threshold_5_q0,
        p_ZL14tree_threshold_6_address0,
        p_ZL14tree_threshold_6_ce0,
        p_ZL14tree_threshold_6_q0,
        p_ZL14tree_threshold_7_address0,
        p_ZL14tree_threshold_7_ce0,
        p_ZL14tree_threshold_7_q0,
        p_ZL14tree_threshold_8_address0,
        p_ZL14tree_threshold_8_ce0,
        p_ZL14tree_threshold_8_q0,
        p_ZL14tree_threshold_9_address0,
        p_ZL14tree_threshold_9_ce0,
        p_ZL14tree_threshold_9_q0,
        p_ZL10tree_right_0_address0,
        p_ZL10tree_right_0_ce0,
        p_ZL10tree_right_0_q0,
        p_ZL10tree_right_1_address0,
        p_ZL10tree_right_1_ce0,
        p_ZL10tree_right_1_q0,
        p_ZL10tree_right_2_address0,
        p_ZL10tree_right_2_ce0,
        p_ZL10tree_right_2_q0,
        p_ZL10tree_right_3_address0,
        p_ZL10tree_right_3_ce0,
        p_ZL10tree_right_3_q0,
        p_ZL10tree_right_4_address0,
        p_ZL10tree_right_4_ce0,
        p_ZL10tree_right_4_q0,
        p_ZL10tree_right_5_address0,
        p_ZL10tree_right_5_ce0,
        p_ZL10tree_right_5_q0,
        p_ZL10tree_right_6_address0,
        p_ZL10tree_right_6_ce0,
        p_ZL10tree_right_6_q0,
        p_ZL10tree_right_7_address0,
        p_ZL10tree_right_7_ce0,
        p_ZL10tree_right_7_q0,
        p_ZL10tree_right_8_address0,
        p_ZL10tree_right_8_ce0,
        p_ZL10tree_right_8_q0,
        p_ZL10tree_right_9_address0,
        p_ZL10tree_right_9_ce0,
        p_ZL10tree_right_9_q0,
        p_ZL9tree_left_0_address0,
        p_ZL9tree_left_0_ce0,
        p_ZL9tree_left_0_q0,
        p_ZL9tree_left_1_address0,
        p_ZL9tree_left_1_ce0,
        p_ZL9tree_left_1_q0,
        p_ZL9tree_left_2_address0,
        p_ZL9tree_left_2_ce0,
        p_ZL9tree_left_2_q0,
        p_ZL9tree_left_3_address0,
        p_ZL9tree_left_3_ce0,
        p_ZL9tree_left_3_q0,
        p_ZL9tree_left_4_address0,
        p_ZL9tree_left_4_ce0,
        p_ZL9tree_left_4_q0,
        p_ZL9tree_left_5_address0,
        p_ZL9tree_left_5_ce0,
        p_ZL9tree_left_5_q0,
        p_ZL9tree_left_6_address0,
        p_ZL9tree_left_6_ce0,
        p_ZL9tree_left_6_q0,
        p_ZL9tree_left_7_address0,
        p_ZL9tree_left_7_ce0,
        p_ZL9tree_left_7_q0,
        p_ZL9tree_left_8_address0,
        p_ZL9tree_left_8_ce0,
        p_ZL9tree_left_8_q0,
        p_ZL9tree_left_9_address0,
        p_ZL9tree_left_9_ce0,
        p_ZL9tree_left_9_q0,
        p_ZL12tree_feature_0_address0,
        p_ZL12tree_feature_0_ce0,
        p_ZL12tree_feature_0_q0,
        p_ZL12tree_feature_1_address0,
        p_ZL12tree_feature_1_ce0,
        p_ZL12tree_feature_1_q0,
        p_ZL12tree_feature_2_address0,
        p_ZL12tree_feature_2_ce0,
        p_ZL12tree_feature_2_q0,
        p_ZL12tree_feature_3_address0,
        p_ZL12tree_feature_3_ce0,
        p_ZL12tree_feature_3_q0,
        p_ZL12tree_feature_4_address0,
        p_ZL12tree_feature_4_ce0,
        p_ZL12tree_feature_4_q0,
        p_ZL12tree_feature_5_address0,
        p_ZL12tree_feature_5_ce0,
        p_ZL12tree_feature_5_q0,
        p_ZL12tree_feature_6_address0,
        p_ZL12tree_feature_6_ce0,
        p_ZL12tree_feature_6_q0,
        p_ZL12tree_feature_7_address0,
        p_ZL12tree_feature_7_ce0,
        p_ZL12tree_feature_7_q0,
        p_ZL12tree_feature_8_address0,
        p_ZL12tree_feature_8_ce0,
        p_ZL12tree_feature_8_q0,
        p_ZL12tree_feature_9_address0,
        p_ZL12tree_feature_9_ce0,
        p_ZL12tree_feature_9_q0
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_pp0_stage0 = 5'd2;
parameter    ap_ST_fsm_pp0_stage1 = 5'd4;
parameter    ap_ST_fsm_state5 = 5'd8;
parameter    ap_ST_fsm_state6 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
input  [15:0] p_read9;
input  [15:0] p_read10;
input  [15:0] p_read11;
input  [15:0] p_read12;
input  [15:0] p_read13;
input  [15:0] p_read14;
input  [15:0] p_read15;
input  [15:0] p_read16;
input  [15:0] p_read17;
input  [15:0] p_read18;
input  [15:0] p_read19;
input  [15:0] p_read20;
input  [15:0] p_read21;
input  [15:0] p_read22;
input  [15:0] p_read23;
input  [15:0] p_read24;
input  [15:0] p_read25;
input  [15:0] p_read26;
input  [15:0] p_read27;
input  [15:0] p_read28;
input  [15:0] p_read29;
input  [15:0] p_read30;
input  [15:0] p_read31;
input  [15:0] p_read32;
input  [15:0] p_read33;
input  [15:0] p_read34;
input  [15:0] p_read35;
input  [15:0] p_read36;
input  [15:0] p_read37;
input  [15:0] p_read38;
input  [15:0] p_read39;
input  [15:0] p_read40;
input  [15:0] p_read41;
input  [15:0] p_read42;
input  [15:0] p_read43;
input  [15:0] p_read44;
input  [15:0] p_read45;
input  [15:0] p_read46;
input  [15:0] p_read47;
input  [15:0] p_read48;
input  [15:0] p_read49;
input  [15:0] p_read50;
input  [15:0] p_read51;
input  [15:0] p_read52;
input  [15:0] p_read53;
input  [15:0] p_read54;
input  [15:0] p_read55;
input  [15:0] p_read56;
input  [15:0] p_read57;
input  [15:0] p_read58;
input  [15:0] p_read59;
input  [15:0] p_read60;
input  [15:0] p_read61;
input  [15:0] p_read62;
input  [15:0] p_read63;
input  [15:0] p_read64;
input  [3:0] tree_id;
output  [7:0] current_out;
output   current_out_ap_vld;
output  [7:0] p_ZL14tree_threshold_0_address0;
output   p_ZL14tree_threshold_0_ce0;
input  [15:0] p_ZL14tree_threshold_0_q0;
output  [7:0] p_ZL14tree_threshold_1_address0;
output   p_ZL14tree_threshold_1_ce0;
input  [15:0] p_ZL14tree_threshold_1_q0;
output  [7:0] p_ZL14tree_threshold_2_address0;
output   p_ZL14tree_threshold_2_ce0;
input  [15:0] p_ZL14tree_threshold_2_q0;
output  [7:0] p_ZL14tree_threshold_3_address0;
output   p_ZL14tree_threshold_3_ce0;
input  [15:0] p_ZL14tree_threshold_3_q0;
output  [7:0] p_ZL14tree_threshold_4_address0;
output   p_ZL14tree_threshold_4_ce0;
input  [15:0] p_ZL14tree_threshold_4_q0;
output  [7:0] p_ZL14tree_threshold_5_address0;
output   p_ZL14tree_threshold_5_ce0;
input  [15:0] p_ZL14tree_threshold_5_q0;
output  [7:0] p_ZL14tree_threshold_6_address0;
output   p_ZL14tree_threshold_6_ce0;
input  [15:0] p_ZL14tree_threshold_6_q0;
output  [7:0] p_ZL14tree_threshold_7_address0;
output   p_ZL14tree_threshold_7_ce0;
input  [15:0] p_ZL14tree_threshold_7_q0;
output  [7:0] p_ZL14tree_threshold_8_address0;
output   p_ZL14tree_threshold_8_ce0;
input  [15:0] p_ZL14tree_threshold_8_q0;
output  [7:0] p_ZL14tree_threshold_9_address0;
output   p_ZL14tree_threshold_9_ce0;
input  [15:0] p_ZL14tree_threshold_9_q0;
output  [7:0] p_ZL10tree_right_0_address0;
output   p_ZL10tree_right_0_ce0;
input  [15:0] p_ZL10tree_right_0_q0;
output  [7:0] p_ZL10tree_right_1_address0;
output   p_ZL10tree_right_1_ce0;
input  [15:0] p_ZL10tree_right_1_q0;
output  [7:0] p_ZL10tree_right_2_address0;
output   p_ZL10tree_right_2_ce0;
input  [15:0] p_ZL10tree_right_2_q0;
output  [7:0] p_ZL10tree_right_3_address0;
output   p_ZL10tree_right_3_ce0;
input  [15:0] p_ZL10tree_right_3_q0;
output  [7:0] p_ZL10tree_right_4_address0;
output   p_ZL10tree_right_4_ce0;
input  [15:0] p_ZL10tree_right_4_q0;
output  [7:0] p_ZL10tree_right_5_address0;
output   p_ZL10tree_right_5_ce0;
input  [15:0] p_ZL10tree_right_5_q0;
output  [7:0] p_ZL10tree_right_6_address0;
output   p_ZL10tree_right_6_ce0;
input  [15:0] p_ZL10tree_right_6_q0;
output  [7:0] p_ZL10tree_right_7_address0;
output   p_ZL10tree_right_7_ce0;
input  [15:0] p_ZL10tree_right_7_q0;
output  [7:0] p_ZL10tree_right_8_address0;
output   p_ZL10tree_right_8_ce0;
input  [15:0] p_ZL10tree_right_8_q0;
output  [7:0] p_ZL10tree_right_9_address0;
output   p_ZL10tree_right_9_ce0;
input  [15:0] p_ZL10tree_right_9_q0;
output  [7:0] p_ZL9tree_left_0_address0;
output   p_ZL9tree_left_0_ce0;
input  [15:0] p_ZL9tree_left_0_q0;
output  [7:0] p_ZL9tree_left_1_address0;
output   p_ZL9tree_left_1_ce0;
input  [15:0] p_ZL9tree_left_1_q0;
output  [7:0] p_ZL9tree_left_2_address0;
output   p_ZL9tree_left_2_ce0;
input  [15:0] p_ZL9tree_left_2_q0;
output  [7:0] p_ZL9tree_left_3_address0;
output   p_ZL9tree_left_3_ce0;
input  [15:0] p_ZL9tree_left_3_q0;
output  [7:0] p_ZL9tree_left_4_address0;
output   p_ZL9tree_left_4_ce0;
input  [15:0] p_ZL9tree_left_4_q0;
output  [7:0] p_ZL9tree_left_5_address0;
output   p_ZL9tree_left_5_ce0;
input  [15:0] p_ZL9tree_left_5_q0;
output  [7:0] p_ZL9tree_left_6_address0;
output   p_ZL9tree_left_6_ce0;
input  [15:0] p_ZL9tree_left_6_q0;
output  [7:0] p_ZL9tree_left_7_address0;
output   p_ZL9tree_left_7_ce0;
input  [15:0] p_ZL9tree_left_7_q0;
output  [7:0] p_ZL9tree_left_8_address0;
output   p_ZL9tree_left_8_ce0;
input  [15:0] p_ZL9tree_left_8_q0;
output  [7:0] p_ZL9tree_left_9_address0;
output   p_ZL9tree_left_9_ce0;
input  [15:0] p_ZL9tree_left_9_q0;
output  [7:0] p_ZL12tree_feature_0_address0;
output   p_ZL12tree_feature_0_ce0;
input  [7:0] p_ZL12tree_feature_0_q0;
output  [7:0] p_ZL12tree_feature_1_address0;
output   p_ZL12tree_feature_1_ce0;
input  [7:0] p_ZL12tree_feature_1_q0;
output  [7:0] p_ZL12tree_feature_2_address0;
output   p_ZL12tree_feature_2_ce0;
input  [7:0] p_ZL12tree_feature_2_q0;
output  [7:0] p_ZL12tree_feature_3_address0;
output   p_ZL12tree_feature_3_ce0;
input  [7:0] p_ZL12tree_feature_3_q0;
output  [7:0] p_ZL12tree_feature_4_address0;
output   p_ZL12tree_feature_4_ce0;
input  [7:0] p_ZL12tree_feature_4_q0;
output  [7:0] p_ZL12tree_feature_5_address0;
output   p_ZL12tree_feature_5_ce0;
input  [7:0] p_ZL12tree_feature_5_q0;
output  [7:0] p_ZL12tree_feature_6_address0;
output   p_ZL12tree_feature_6_ce0;
input  [7:0] p_ZL12tree_feature_6_q0;
output  [7:0] p_ZL12tree_feature_7_address0;
output   p_ZL12tree_feature_7_ce0;
input  [7:0] p_ZL12tree_feature_7_q0;
output  [7:0] p_ZL12tree_feature_8_address0;
output   p_ZL12tree_feature_8_ce0;
input  [7:0] p_ZL12tree_feature_8_q0;
output  [7:0] p_ZL12tree_feature_9_address0;
output   p_ZL12tree_feature_9_ce0;
input  [7:0] p_ZL12tree_feature_9_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] current_out;
reg current_out_ap_vld;
reg p_ZL14tree_threshold_0_ce0;
reg p_ZL14tree_threshold_1_ce0;
reg p_ZL14tree_threshold_2_ce0;
reg p_ZL14tree_threshold_3_ce0;
reg p_ZL14tree_threshold_4_ce0;
reg p_ZL14tree_threshold_5_ce0;
reg p_ZL14tree_threshold_6_ce0;
reg p_ZL14tree_threshold_7_ce0;
reg p_ZL14tree_threshold_8_ce0;
reg p_ZL14tree_threshold_9_ce0;
reg p_ZL10tree_right_0_ce0;
reg p_ZL10tree_right_1_ce0;
reg p_ZL10tree_right_2_ce0;
reg p_ZL10tree_right_3_ce0;
reg p_ZL10tree_right_4_ce0;
reg p_ZL10tree_right_5_ce0;
reg p_ZL10tree_right_6_ce0;
reg p_ZL10tree_right_7_ce0;
reg p_ZL10tree_right_8_ce0;
reg p_ZL10tree_right_9_ce0;
reg p_ZL9tree_left_0_ce0;
reg p_ZL9tree_left_1_ce0;
reg p_ZL9tree_left_2_ce0;
reg p_ZL9tree_left_3_ce0;
reg p_ZL9tree_left_4_ce0;
reg p_ZL9tree_left_5_ce0;
reg p_ZL9tree_left_6_ce0;
reg p_ZL9tree_left_7_ce0;
reg p_ZL9tree_left_8_ce0;
reg p_ZL9tree_left_9_ce0;
reg p_ZL12tree_feature_0_ce0;
reg p_ZL12tree_feature_1_ce0;
reg p_ZL12tree_feature_2_ce0;
reg p_ZL12tree_feature_3_ce0;
reg p_ZL12tree_feature_4_ce0;
reg p_ZL12tree_feature_5_ce0;
reg p_ZL12tree_feature_6_ce0;
reg p_ZL12tree_feature_7_ce0;
reg p_ZL12tree_feature_8_ce0;
reg p_ZL12tree_feature_9_ce0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln33_fu_1200_p2;
reg   [0:0] icmp_ln33_reg_1780;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [8:0] d_2_fu_1206_p2;
reg   [8:0] d_2_reg_1784;
reg   [7:0] grp_load_fu_1183_p1;
reg   [7:0] current_load_1_reg_1789;
wire   [63:0] zext_ln36_fu_1212_p1;
reg   [63:0] zext_ln36_reg_1794;
wire   [5:0] trunc_ln1652_fu_1259_p1;
reg   [5:0] trunc_ln1652_reg_1881;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_11001;
wire   [0:0] tmp_fu_1251_p3;
wire    ap_block_pp0_stage1_subdone;
reg    ap_predicate_tran3to5_state3;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage1;
reg   [7:0] current_fu_258;
wire   [7:0] current_1_fu_1425_p3;
reg   [7:0] ap_sig_allocacmp_current_load_1;
wire    ap_CS_fsm_state6;
reg   [8:0] d_fu_262;
wire    ap_CS_fsm_state5;
wire   [7:0] fidx_V_fu_1226_p12;
wire   [15:0] tmp_1_fu_1267_p66;
wire   [15:0] tmp_2_fu_1336_p12;
wire   [15:0] tmp_3_fu_1367_p12;
wire   [15:0] tmp_4_fu_1392_p12;
wire   [0:0] icmp_ln1652_fu_1361_p2;
wire   [7:0] trunc_ln1652_1_fu_1417_p1;
wire   [7:0] trunc_ln1652_2_fu_1421_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

rf_accel_mux_104_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
mux_104_8_1_1_U70(
    .din0(p_ZL12tree_feature_0_q0),
    .din1(p_ZL12tree_feature_1_q0),
    .din2(p_ZL12tree_feature_2_q0),
    .din3(p_ZL12tree_feature_3_q0),
    .din4(p_ZL12tree_feature_4_q0),
    .din5(p_ZL12tree_feature_5_q0),
    .din6(p_ZL12tree_feature_6_q0),
    .din7(p_ZL12tree_feature_7_q0),
    .din8(p_ZL12tree_feature_8_q0),
    .din9(p_ZL12tree_feature_9_q0),
    .din10(tree_id),
    .dout(fidx_V_fu_1226_p12)
);

rf_accel_mux_646_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 16 ),
    .din26_WIDTH( 16 ),
    .din27_WIDTH( 16 ),
    .din28_WIDTH( 16 ),
    .din29_WIDTH( 16 ),
    .din30_WIDTH( 16 ),
    .din31_WIDTH( 16 ),
    .din32_WIDTH( 16 ),
    .din33_WIDTH( 16 ),
    .din34_WIDTH( 16 ),
    .din35_WIDTH( 16 ),
    .din36_WIDTH( 16 ),
    .din37_WIDTH( 16 ),
    .din38_WIDTH( 16 ),
    .din39_WIDTH( 16 ),
    .din40_WIDTH( 16 ),
    .din41_WIDTH( 16 ),
    .din42_WIDTH( 16 ),
    .din43_WIDTH( 16 ),
    .din44_WIDTH( 16 ),
    .din45_WIDTH( 16 ),
    .din46_WIDTH( 16 ),
    .din47_WIDTH( 16 ),
    .din48_WIDTH( 16 ),
    .din49_WIDTH( 16 ),
    .din50_WIDTH( 16 ),
    .din51_WIDTH( 16 ),
    .din52_WIDTH( 16 ),
    .din53_WIDTH( 16 ),
    .din54_WIDTH( 16 ),
    .din55_WIDTH( 16 ),
    .din56_WIDTH( 16 ),
    .din57_WIDTH( 16 ),
    .din58_WIDTH( 16 ),
    .din59_WIDTH( 16 ),
    .din60_WIDTH( 16 ),
    .din61_WIDTH( 16 ),
    .din62_WIDTH( 16 ),
    .din63_WIDTH( 16 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mux_646_16_1_1_U71(
    .din0(p_read1),
    .din1(p_read2),
    .din2(p_read3),
    .din3(p_read4),
    .din4(p_read5),
    .din5(p_read6),
    .din6(p_read7),
    .din7(p_read8),
    .din8(p_read9),
    .din9(p_read10),
    .din10(p_read11),
    .din11(p_read12),
    .din12(p_read13),
    .din13(p_read14),
    .din14(p_read15),
    .din15(p_read16),
    .din16(p_read17),
    .din17(p_read18),
    .din18(p_read19),
    .din19(p_read20),
    .din20(p_read21),
    .din21(p_read22),
    .din22(p_read23),
    .din23(p_read24),
    .din24(p_read25),
    .din25(p_read26),
    .din26(p_read27),
    .din27(p_read28),
    .din28(p_read29),
    .din29(p_read30),
    .din30(p_read31),
    .din31(p_read32),
    .din32(p_read33),
    .din33(p_read34),
    .din34(p_read35),
    .din35(p_read36),
    .din36(p_read37),
    .din37(p_read38),
    .din38(p_read39),
    .din39(p_read40),
    .din40(p_read41),
    .din41(p_read42),
    .din42(p_read43),
    .din43(p_read44),
    .din44(p_read45),
    .din45(p_read46),
    .din46(p_read47),
    .din47(p_read48),
    .din48(p_read49),
    .din49(p_read50),
    .din50(p_read51),
    .din51(p_read52),
    .din52(p_read53),
    .din53(p_read54),
    .din54(p_read55),
    .din55(p_read56),
    .din56(p_read57),
    .din57(p_read58),
    .din58(p_read59),
    .din59(p_read60),
    .din60(p_read61),
    .din61(p_read62),
    .din62(p_read63),
    .din63(p_read64),
    .din64(trunc_ln1652_reg_1881),
    .dout(tmp_1_fu_1267_p66)
);

rf_accel_mux_104_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
mux_104_16_1_1_U72(
    .din0(p_ZL14tree_threshold_0_q0),
    .din1(p_ZL14tree_threshold_1_q0),
    .din2(p_ZL14tree_threshold_2_q0),
    .din3(p_ZL14tree_threshold_3_q0),
    .din4(p_ZL14tree_threshold_4_q0),
    .din5(p_ZL14tree_threshold_5_q0),
    .din6(p_ZL14tree_threshold_6_q0),
    .din7(p_ZL14tree_threshold_7_q0),
    .din8(p_ZL14tree_threshold_8_q0),
    .din9(p_ZL14tree_threshold_9_q0),
    .din10(tree_id),
    .dout(tmp_2_fu_1336_p12)
);

rf_accel_mux_104_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
mux_104_16_1_1_U73(
    .din0(p_ZL10tree_right_0_q0),
    .din1(p_ZL10tree_right_1_q0),
    .din2(p_ZL10tree_right_2_q0),
    .din3(p_ZL10tree_right_3_q0),
    .din4(p_ZL10tree_right_4_q0),
    .din5(p_ZL10tree_right_5_q0),
    .din6(p_ZL10tree_right_6_q0),
    .din7(p_ZL10tree_right_7_q0),
    .din8(p_ZL10tree_right_8_q0),
    .din9(p_ZL10tree_right_9_q0),
    .din10(tree_id),
    .dout(tmp_3_fu_1367_p12)
);

rf_accel_mux_104_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
mux_104_16_1_1_U74(
    .din0(p_ZL9tree_left_0_q0),
    .din1(p_ZL9tree_left_1_q0),
    .din2(p_ZL9tree_left_2_q0),
    .din3(p_ZL9tree_left_3_q0),
    .din4(p_ZL9tree_left_4_q0),
    .din5(p_ZL9tree_left_5_q0),
    .din6(p_ZL9tree_left_6_q0),
    .din7(p_ZL9tree_left_7_q0),
    .din8(p_ZL9tree_left_8_q0),
    .din9(p_ZL9tree_left_9_q0),
    .din10(tree_id),
    .dout(tmp_4_fu_1392_p12)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        current_fu_258 <= 8'd0;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_fu_258 <= current_1_fu_1425_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        d_fu_262 <= 9'd0;
    end else if (((tmp_fu_1251_p3 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln33_reg_1780 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        d_fu_262 <= d_2_reg_1784;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln33_fu_1200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_load_1_reg_1789 <= grp_load_fu_1183_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        d_2_reg_1784 <= d_2_fu_1206_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln33_reg_1780 <= icmp_ln33_fu_1200_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_1251_p3 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln33_reg_1780 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        trunc_ln1652_reg_1881 <= trunc_ln1652_fu_1259_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln33_fu_1200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln36_reg_1794[7 : 0] <= zext_ln36_fu_1212_p1[7 : 0];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((ap_predicate_tran3to5_state3 == 1'b1) | (icmp_ln33_reg_1780 == 1'd1))) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_current_load_1 = current_1_fu_1425_p3;
    end else begin
        ap_sig_allocacmp_current_load_1 = current_fu_258;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        current_out = grp_load_fu_1183_p1;
    end else if (((icmp_ln33_reg_1780 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        current_out = current_load_1_reg_1789;
    end else begin
        current_out = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((icmp_ln33_reg_1780 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        current_out_ap_vld = 1'b1;
    end else begin
        current_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_load_fu_1183_p1 = current_fu_258;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln33_fu_1200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_load_fu_1183_p1 = ap_sig_allocacmp_current_load_1;
    end else begin
        grp_load_fu_1183_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL10tree_right_0_ce0 = 1'b1;
    end else begin
        p_ZL10tree_right_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL10tree_right_1_ce0 = 1'b1;
    end else begin
        p_ZL10tree_right_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL10tree_right_2_ce0 = 1'b1;
    end else begin
        p_ZL10tree_right_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL10tree_right_3_ce0 = 1'b1;
    end else begin
        p_ZL10tree_right_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL10tree_right_4_ce0 = 1'b1;
    end else begin
        p_ZL10tree_right_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL10tree_right_5_ce0 = 1'b1;
    end else begin
        p_ZL10tree_right_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL10tree_right_6_ce0 = 1'b1;
    end else begin
        p_ZL10tree_right_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL10tree_right_7_ce0 = 1'b1;
    end else begin
        p_ZL10tree_right_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL10tree_right_8_ce0 = 1'b1;
    end else begin
        p_ZL10tree_right_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL10tree_right_9_ce0 = 1'b1;
    end else begin
        p_ZL10tree_right_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL12tree_feature_0_ce0 = 1'b1;
    end else begin
        p_ZL12tree_feature_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL12tree_feature_1_ce0 = 1'b1;
    end else begin
        p_ZL12tree_feature_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL12tree_feature_2_ce0 = 1'b1;
    end else begin
        p_ZL12tree_feature_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL12tree_feature_3_ce0 = 1'b1;
    end else begin
        p_ZL12tree_feature_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL12tree_feature_4_ce0 = 1'b1;
    end else begin
        p_ZL12tree_feature_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL12tree_feature_5_ce0 = 1'b1;
    end else begin
        p_ZL12tree_feature_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL12tree_feature_6_ce0 = 1'b1;
    end else begin
        p_ZL12tree_feature_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL12tree_feature_7_ce0 = 1'b1;
    end else begin
        p_ZL12tree_feature_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL12tree_feature_8_ce0 = 1'b1;
    end else begin
        p_ZL12tree_feature_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL12tree_feature_9_ce0 = 1'b1;
    end else begin
        p_ZL12tree_feature_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL14tree_threshold_0_ce0 = 1'b1;
    end else begin
        p_ZL14tree_threshold_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL14tree_threshold_1_ce0 = 1'b1;
    end else begin
        p_ZL14tree_threshold_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL14tree_threshold_2_ce0 = 1'b1;
    end else begin
        p_ZL14tree_threshold_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL14tree_threshold_3_ce0 = 1'b1;
    end else begin
        p_ZL14tree_threshold_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL14tree_threshold_4_ce0 = 1'b1;
    end else begin
        p_ZL14tree_threshold_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL14tree_threshold_5_ce0 = 1'b1;
    end else begin
        p_ZL14tree_threshold_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL14tree_threshold_6_ce0 = 1'b1;
    end else begin
        p_ZL14tree_threshold_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL14tree_threshold_7_ce0 = 1'b1;
    end else begin
        p_ZL14tree_threshold_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL14tree_threshold_8_ce0 = 1'b1;
    end else begin
        p_ZL14tree_threshold_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL14tree_threshold_9_ce0 = 1'b1;
    end else begin
        p_ZL14tree_threshold_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL9tree_left_0_ce0 = 1'b1;
    end else begin
        p_ZL9tree_left_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL9tree_left_1_ce0 = 1'b1;
    end else begin
        p_ZL9tree_left_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL9tree_left_2_ce0 = 1'b1;
    end else begin
        p_ZL9tree_left_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL9tree_left_3_ce0 = 1'b1;
    end else begin
        p_ZL9tree_left_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL9tree_left_4_ce0 = 1'b1;
    end else begin
        p_ZL9tree_left_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL9tree_left_5_ce0 = 1'b1;
    end else begin
        p_ZL9tree_left_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL9tree_left_6_ce0 = 1'b1;
    end else begin
        p_ZL9tree_left_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL9tree_left_7_ce0 = 1'b1;
    end else begin
        p_ZL9tree_left_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL9tree_left_8_ce0 = 1'b1;
    end else begin
        p_ZL9tree_left_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL9tree_left_9_ce0 = 1'b1;
    end else begin
        p_ZL9tree_left_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~(((ap_predicate_tran3to5_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln33_reg_1780 == 1'd1))) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln33_reg_1780 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((ap_predicate_tran3to5_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_tran3to5_state3 = ((tmp_fu_1251_p3 == 1'd1) & (icmp_ln33_reg_1780 == 1'd0));
end

assign current_1_fu_1425_p3 = ((icmp_ln1652_fu_1361_p2[0:0] == 1'b1) ? trunc_ln1652_1_fu_1417_p1 : trunc_ln1652_2_fu_1421_p1);

assign d_2_fu_1206_p2 = (d_fu_262 + 9'd1);

assign icmp_ln1652_fu_1361_p2 = (($signed(tmp_1_fu_1267_p66) > $signed(tmp_2_fu_1336_p12)) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_1200_p2 = ((d_fu_262 == 9'd256) ? 1'b1 : 1'b0);

assign p_ZL10tree_right_0_address0 = zext_ln36_reg_1794;

assign p_ZL10tree_right_1_address0 = zext_ln36_reg_1794;

assign p_ZL10tree_right_2_address0 = zext_ln36_reg_1794;

assign p_ZL10tree_right_3_address0 = zext_ln36_reg_1794;

assign p_ZL10tree_right_4_address0 = zext_ln36_reg_1794;

assign p_ZL10tree_right_5_address0 = zext_ln36_reg_1794;

assign p_ZL10tree_right_6_address0 = zext_ln36_reg_1794;

assign p_ZL10tree_right_7_address0 = zext_ln36_reg_1794;

assign p_ZL10tree_right_8_address0 = zext_ln36_reg_1794;

assign p_ZL10tree_right_9_address0 = zext_ln36_reg_1794;

assign p_ZL12tree_feature_0_address0 = zext_ln36_fu_1212_p1;

assign p_ZL12tree_feature_1_address0 = zext_ln36_fu_1212_p1;

assign p_ZL12tree_feature_2_address0 = zext_ln36_fu_1212_p1;

assign p_ZL12tree_feature_3_address0 = zext_ln36_fu_1212_p1;

assign p_ZL12tree_feature_4_address0 = zext_ln36_fu_1212_p1;

assign p_ZL12tree_feature_5_address0 = zext_ln36_fu_1212_p1;

assign p_ZL12tree_feature_6_address0 = zext_ln36_fu_1212_p1;

assign p_ZL12tree_feature_7_address0 = zext_ln36_fu_1212_p1;

assign p_ZL12tree_feature_8_address0 = zext_ln36_fu_1212_p1;

assign p_ZL12tree_feature_9_address0 = zext_ln36_fu_1212_p1;

assign p_ZL14tree_threshold_0_address0 = zext_ln36_reg_1794;

assign p_ZL14tree_threshold_1_address0 = zext_ln36_reg_1794;

assign p_ZL14tree_threshold_2_address0 = zext_ln36_reg_1794;

assign p_ZL14tree_threshold_3_address0 = zext_ln36_reg_1794;

assign p_ZL14tree_threshold_4_address0 = zext_ln36_reg_1794;

assign p_ZL14tree_threshold_5_address0 = zext_ln36_reg_1794;

assign p_ZL14tree_threshold_6_address0 = zext_ln36_reg_1794;

assign p_ZL14tree_threshold_7_address0 = zext_ln36_reg_1794;

assign p_ZL14tree_threshold_8_address0 = zext_ln36_reg_1794;

assign p_ZL14tree_threshold_9_address0 = zext_ln36_reg_1794;

assign p_ZL9tree_left_0_address0 = zext_ln36_reg_1794;

assign p_ZL9tree_left_1_address0 = zext_ln36_reg_1794;

assign p_ZL9tree_left_2_address0 = zext_ln36_reg_1794;

assign p_ZL9tree_left_3_address0 = zext_ln36_reg_1794;

assign p_ZL9tree_left_4_address0 = zext_ln36_reg_1794;

assign p_ZL9tree_left_5_address0 = zext_ln36_reg_1794;

assign p_ZL9tree_left_6_address0 = zext_ln36_reg_1794;

assign p_ZL9tree_left_7_address0 = zext_ln36_reg_1794;

assign p_ZL9tree_left_8_address0 = zext_ln36_reg_1794;

assign p_ZL9tree_left_9_address0 = zext_ln36_reg_1794;

assign tmp_fu_1251_p3 = fidx_V_fu_1226_p12[32'd7];

assign trunc_ln1652_1_fu_1417_p1 = tmp_3_fu_1367_p12[7:0];

assign trunc_ln1652_2_fu_1421_p1 = tmp_4_fu_1392_p12[7:0];

assign trunc_ln1652_fu_1259_p1 = fidx_V_fu_1226_p12[5:0];

assign zext_ln36_fu_1212_p1 = grp_load_fu_1183_p1;

always @ (posedge ap_clk) begin
    zext_ln36_reg_1794[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //rf_accel_traverse_tree_Pipeline_TREE_WALK
