// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dt_accel_dt_accel_Pipeline_LOAD_NODES (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        num_nodes,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        node_feature_V_address0,
        node_feature_V_ce0,
        node_feature_V_we0,
        node_feature_V_d0,
        node_threshold_V_address0,
        node_threshold_V_ce0,
        node_threshold_V_we0,
        node_threshold_V_d0,
        node_left_V_address0,
        node_left_V_ce0,
        node_left_V_we0,
        node_left_V_d0,
        node_right_V_address0,
        node_right_V_ce0,
        node_right_V_we0,
        node_right_V_d0,
        node_class_V_address0,
        node_class_V_ce0,
        node_class_V_we0,
        node_class_V_d0
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input  [31:0] num_nodes;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [8:0] node_feature_V_address0;
output   node_feature_V_ce0;
output   node_feature_V_we0;
output  [7:0] node_feature_V_d0;
output  [8:0] node_threshold_V_address0;
output   node_threshold_V_ce0;
output   node_threshold_V_we0;
output  [15:0] node_threshold_V_d0;
output  [8:0] node_left_V_address0;
output   node_left_V_ce0;
output   node_left_V_we0;
output  [8:0] node_left_V_d0;
output  [8:0] node_right_V_address0;
output   node_right_V_ce0;
output   node_right_V_we0;
output  [8:0] node_right_V_d0;
output  [8:0] node_class_V_address0;
output   node_class_V_ce0;
output   node_class_V_we0;
output  [7:0] node_class_V_d0;

reg ap_idle;
reg in_stream_TREADY;
reg node_feature_V_ce0;
reg node_feature_V_we0;
reg node_threshold_V_ce0;
reg node_threshold_V_we0;
reg node_left_V_ce0;
reg node_left_V_we0;
reg node_right_V_ce0;
reg node_right_V_we0;
reg node_class_V_ce0;
reg node_class_V_we0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln42_fu_169_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state5;
reg    ap_block_state5_pp0_stage4_iter0;
reg    in_stream_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln42_fu_181_p1;
reg   [63:0] zext_ln42_reg_226;
reg   [8:0] n_fu_66;
wire   [8:0] add_ln42_fu_175_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_n_1;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state3_pp0_stage2_iter0;
reg    ap_block_state4_pp0_stage3_iter0;
wire   [31:0] zext_ln42_1_fu_165_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_start_int;
reg    ap_condition_213;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_done_reg = 1'b0;
end

dt_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln42_fu_169_p2 == 1'd1) & (in_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_213)) begin
        if ((icmp_ln42_fu_169_p2 == 1'd1)) begin
            n_fu_66 <= add_ln42_fu_175_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_66 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln42_fu_169_p2 == 1'd1) & (in_stream_TVALID == 1'b0))) & (icmp_ln42_fu_169_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        zext_ln42_reg_226[8 : 0] <= zext_ln42_fu_181_p1[8 : 0];
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln42_fu_169_p2 == 1'd1) & (in_stream_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((in_stream_TVALID == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((in_stream_TVALID == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((in_stream_TVALID == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((in_stream_TVALID == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln42_fu_169_p2 == 1'd1) & (in_stream_TVALID == 1'b0))) & (icmp_ln42_fu_169_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln42_fu_169_p2 == 1'd1) & (in_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_n_1 = 9'd0;
    end else begin
        ap_sig_allocacmp_n_1 = n_fu_66;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((icmp_ln42_fu_169_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2)) | ((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | (~((ap_start_int == 1'b0) | ((icmp_ln42_fu_169_p2 == 1'd1) & (in_stream_TVALID == 1'b0))) & (icmp_ln42_fu_169_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        node_class_V_ce0 = 1'b1;
    end else begin
        node_class_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        node_class_V_we0 = 1'b1;
    end else begin
        node_class_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln42_fu_169_p2 == 1'd1) & (in_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        node_feature_V_ce0 = 1'b1;
    end else begin
        node_feature_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln42_fu_169_p2 == 1'd1) & (in_stream_TVALID == 1'b0))) & (icmp_ln42_fu_169_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        node_feature_V_we0 = 1'b1;
    end else begin
        node_feature_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        node_left_V_ce0 = 1'b1;
    end else begin
        node_left_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        node_left_V_we0 = 1'b1;
    end else begin
        node_left_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        node_right_V_ce0 = 1'b1;
    end else begin
        node_right_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        node_right_V_we0 = 1'b1;
    end else begin
        node_right_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        node_threshold_V_ce0 = 1'b1;
    end else begin
        node_threshold_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        node_threshold_V_we0 = 1'b1;
    end else begin
        node_threshold_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start_int == 1'b0) | ((icmp_ln42_fu_169_p2 == 1'd1) & (in_stream_TVALID == 1'b0))) & (icmp_ln42_fu_169_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((ap_start_int == 1'b0) | ((icmp_ln42_fu_169_p2 == 1'd1) & (in_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((in_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln42_fu_175_p2 = (ap_sig_allocacmp_n_1 + 9'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln42_fu_169_p2 == 1'd1) & (in_stream_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (in_stream_TVALID == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = (in_stream_TVALID == 1'b0);
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = (in_stream_TVALID == 1'b0);
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0 = (in_stream_TVALID == 1'b0);
end

always @ (*) begin
    ap_condition_213 = (~((ap_start_int == 1'b0) | ((icmp_ln42_fu_169_p2 == 1'd1) & (in_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln42_fu_169_p2 = (($signed(zext_ln42_1_fu_165_p1) < $signed(num_nodes)) ? 1'b1 : 1'b0);

assign node_class_V_address0 = zext_ln42_reg_226;

assign node_class_V_d0 = in_stream_TDATA[7:0];

assign node_feature_V_address0 = zext_ln42_fu_181_p1;

assign node_feature_V_d0 = in_stream_TDATA[7:0];

assign node_left_V_address0 = zext_ln42_reg_226;

assign node_left_V_d0 = in_stream_TDATA[8:0];

assign node_right_V_address0 = zext_ln42_reg_226;

assign node_right_V_d0 = in_stream_TDATA[8:0];

assign node_threshold_V_address0 = zext_ln42_reg_226;

assign node_threshold_V_d0 = in_stream_TDATA[15:0];

assign zext_ln42_1_fu_165_p1 = ap_sig_allocacmp_n_1;

assign zext_ln42_fu_181_p1 = ap_sig_allocacmp_n_1;

always @ (posedge ap_clk) begin
    zext_ln42_reg_226[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //dt_accel_dt_accel_Pipeline_LOAD_NODES
