// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module svm_accel_svm_accel_Pipeline_ARGMAX (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        best_votes_3,
        num_classes,
        votes_8,
        votes_7,
        votes_6,
        votes_5,
        votes_4,
        votes_3,
        votes_2,
        votes_1,
        votes,
        best_class_out,
        best_class_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] best_votes_3;
input  [31:0] num_classes;
input  [31:0] votes_8;
input  [31:0] votes_7;
input  [31:0] votes_6;
input  [31:0] votes_5;
input  [31:0] votes_4;
input  [31:0] votes_3;
input  [31:0] votes_2;
input  [31:0] votes_1;
input  [31:0] votes;
output  [31:0] best_class_out;
output   best_class_out_ap_vld;

reg ap_idle;
reg best_class_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln193_fu_159_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [31:0] zext_ln193_fu_155_p1;
reg   [31:0] zext_ln193_reg_267;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] tmp_fu_169_p12;
reg   [31:0] tmp_reg_275;
reg   [31:0] best_class_fu_52;
wire   [31:0] best_class_1_fu_217_p3;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg   [31:0] best_votes_fu_56;
wire   [31:0] best_votes_1_fu_224_p3;
reg   [30:0] c_1_fu_60;
wire   [30:0] add_ln193_fu_195_p2;
reg   [30:0] ap_sig_allocacmp_c;
wire    ap_block_pp0_stage0_01001;
wire   [3:0] tmp_fu_169_p11;
wire   [0:0] icmp_ln196_fu_212_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

svm_accel_mux_104_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_104_32_1_1_U351(
    .din0(best_votes_3),
    .din1(votes_8),
    .din2(votes_7),
    .din3(votes_6),
    .din4(votes_5),
    .din5(votes_4),
    .din6(votes_3),
    .din7(votes_2),
    .din8(votes_1),
    .din9(votes),
    .din10(tmp_fu_169_p11),
    .dout(tmp_fu_169_p12)
);

svm_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            best_class_fu_52 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            best_class_fu_52 <= best_class_1_fu_217_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            best_votes_fu_56 <= best_votes_3;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            best_votes_fu_56 <= best_votes_1_fu_224_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln193_fu_159_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_1_fu_60 <= add_ln193_fu_195_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_1_fu_60 <= 31'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln193_fu_159_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_275 <= tmp_fu_169_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln193_reg_267[30 : 0] <= zext_ln193_fu_155_p1[30 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln193_fu_159_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c = 31'd1;
    end else begin
        ap_sig_allocacmp_c = c_1_fu_60;
    end
end

always @ (*) begin
    if (((icmp_ln193_fu_159_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        best_class_out_ap_vld = 1'b1;
    end else begin
        best_class_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln193_fu_195_p2 = (ap_sig_allocacmp_c + 31'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign best_class_1_fu_217_p3 = ((icmp_ln196_fu_212_p2[0:0] == 1'b1) ? zext_ln193_reg_267 : best_class_fu_52);

assign best_class_out = best_class_fu_52;

assign best_votes_1_fu_224_p3 = ((icmp_ln196_fu_212_p2[0:0] == 1'b1) ? tmp_reg_275 : best_votes_fu_56);

assign icmp_ln193_fu_159_p2 = (($signed(zext_ln193_fu_155_p1) < $signed(num_classes)) ? 1'b1 : 1'b0);

assign icmp_ln196_fu_212_p2 = (($signed(best_votes_fu_56) < $signed(tmp_reg_275)) ? 1'b1 : 1'b0);

assign tmp_fu_169_p11 = ap_sig_allocacmp_c[3:0];

assign zext_ln193_fu_155_p1 = ap_sig_allocacmp_c;

always @ (posedge ap_clk) begin
    zext_ln193_reg_267[31] <= 1'b0;
end

endmodule //svm_accel_svm_accel_Pipeline_ARGMAX
