// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mlp_accel_mlp_accel_Pipeline_L2_DOT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln164,
        h1_size,
        n_5,
        trunc_ln837,
        h1_V_address0,
        h1_V_ce0,
        h1_V_q0,
        sum_V_16_out,
        sum_V_16_out_ap_vld,
        p_ZL2w2_0_address0,
        p_ZL2w2_0_ce0,
        p_ZL2w2_0_q0,
        p_ZL2w2_1_address0,
        p_ZL2w2_1_ce0,
        p_ZL2w2_1_q0,
        p_ZL2w2_2_address0,
        p_ZL2w2_2_ce0,
        p_ZL2w2_2_q0,
        p_ZL2w2_3_address0,
        p_ZL2w2_3_ce0,
        p_ZL2w2_3_q0,
        p_ZL2w2_4_address0,
        p_ZL2w2_4_ce0,
        p_ZL2w2_4_q0,
        p_ZL2w2_5_address0,
        p_ZL2w2_5_ce0,
        p_ZL2w2_5_q0,
        p_ZL2w2_6_address0,
        p_ZL2w2_6_ce0,
        p_ZL2w2_6_q0,
        p_ZL2w2_7_address0,
        p_ZL2w2_7_ce0,
        p_ZL2w2_7_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] sext_ln164;
input  [31:0] h1_size;
input  [6:0] n_5;
input  [2:0] trunc_ln837;
output  [5:0] h1_V_address0;
output   h1_V_ce0;
input  [15:0] h1_V_q0;
output  [31:0] sum_V_16_out;
output   sum_V_16_out_ap_vld;
output  [8:0] p_ZL2w2_0_address0;
output   p_ZL2w2_0_ce0;
input  [15:0] p_ZL2w2_0_q0;
output  [8:0] p_ZL2w2_1_address0;
output   p_ZL2w2_1_ce0;
input  [15:0] p_ZL2w2_1_q0;
output  [8:0] p_ZL2w2_2_address0;
output   p_ZL2w2_2_ce0;
input  [15:0] p_ZL2w2_2_q0;
output  [8:0] p_ZL2w2_3_address0;
output   p_ZL2w2_3_ce0;
input  [15:0] p_ZL2w2_3_q0;
output  [8:0] p_ZL2w2_4_address0;
output   p_ZL2w2_4_ce0;
input  [15:0] p_ZL2w2_4_q0;
output  [8:0] p_ZL2w2_5_address0;
output   p_ZL2w2_5_ce0;
input  [15:0] p_ZL2w2_5_q0;
output  [8:0] p_ZL2w2_6_address0;
output   p_ZL2w2_6_ce0;
input  [15:0] p_ZL2w2_6_q0;
output  [8:0] p_ZL2w2_7_address0;
output   p_ZL2w2_7_ce0;
input  [15:0] p_ZL2w2_7_q0;

reg ap_idle;
reg h1_V_ce0;
reg sum_V_16_out_ap_vld;
reg p_ZL2w2_0_ce0;
reg p_ZL2w2_1_ce0;
reg p_ZL2w2_2_ce0;
reg p_ZL2w2_3_ce0;
reg p_ZL2w2_4_ce0;
reg p_ZL2w2_5_ce0;
reg p_ZL2w2_6_ce0;
reg p_ZL2w2_7_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln166_fu_259_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln166_reg_443;
reg   [0:0] icmp_ln166_reg_443_pp0_iter1_reg;
wire   [0:0] icmp_ln168_fu_280_p2;
reg   [0:0] icmp_ln168_reg_447;
reg   [0:0] icmp_ln168_reg_447_pp0_iter1_reg;
reg   [0:0] icmp_ln168_reg_447_pp0_iter2_reg;
wire   [2:0] trunc_ln837_1_fu_328_p1;
reg   [2:0] trunc_ln837_1_reg_492;
wire   [15:0] tmp_7_fu_337_p10;
reg   [15:0] tmp_7_reg_502;
reg   [15:0] h1_V_load_reg_507;
wire   [47:0] r_V_2_fu_380_p2;
reg   [47:0] r_V_2_reg_512;
wire   [63:0] zext_ln837_fu_316_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln166_fu_271_p1;
reg   [31:0] lhs_fu_86;
wire   [31:0] sum_V_2_fu_412_p3;
wire  signed [31:0] sext_ln164_cast_fu_242_p1;
wire    ap_loop_init;
reg   [6:0] m_2_fu_90;
wire   [6:0] add_ln166_fu_265_p2;
reg   [6:0] ap_sig_allocacmp_m;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] zext_ln166_1_fu_276_p1;
wire   [2:0] tmp_6_cast_fu_296_p4;
wire   [2:0] lshr_ln837_1_fu_286_p4;
wire   [8:0] tmp_8_fu_306_p4;
wire  signed [23:0] r_V_fu_358_p3;
wire  signed [23:0] shl_ln838_3_fu_365_p3;
wire   [47:0] lhs_2_fu_389_p3;
wire   [47:0] ret_V_fu_397_p2;
wire   [31:0] sum_V_fu_402_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

mlp_accel_mux_83_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
mux_83_16_1_1_U25(
    .din0(p_ZL2w2_0_q0),
    .din1(p_ZL2w2_1_q0),
    .din2(p_ZL2w2_2_q0),
    .din3(p_ZL2w2_3_q0),
    .din4(p_ZL2w2_4_q0),
    .din5(p_ZL2w2_5_q0),
    .din6(p_ZL2w2_6_q0),
    .din7(p_ZL2w2_7_q0),
    .din8(trunc_ln837_1_reg_492),
    .dout(tmp_7_fu_337_p10)
);

mlp_accel_mul_24s_24s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 48 ))
mul_24s_24s_48_1_1_U26(
    .din0(shl_ln838_3_fu_365_p3),
    .din1(r_V_fu_358_p3),
    .dout(r_V_2_fu_380_p2)
);

mlp_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            lhs_fu_86 <= sext_ln164_cast_fu_242_p1;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            lhs_fu_86 <= sum_V_2_fu_412_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln166_fu_259_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            m_2_fu_90 <= add_ln166_fu_265_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            m_2_fu_90 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        h1_V_load_reg_507 <= h1_V_q0;
        icmp_ln166_reg_443 <= icmp_ln166_fu_259_p2;
        icmp_ln166_reg_443_pp0_iter1_reg <= icmp_ln166_reg_443;
        icmp_ln168_reg_447_pp0_iter1_reg <= icmp_ln168_reg_447;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln166_fu_259_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln168_reg_447 <= icmp_ln168_fu_280_p2;
        trunc_ln837_1_reg_492 <= trunc_ln837_1_fu_328_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln168_reg_447_pp0_iter2_reg <= icmp_ln168_reg_447_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln168_reg_447_pp0_iter1_reg == 1'd1))) begin
        r_V_2_reg_512 <= r_V_2_fu_380_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln168_reg_447 == 1'd1))) begin
        tmp_7_reg_502 <= tmp_7_fu_337_p10;
    end
end

always @ (*) begin
    if (((icmp_ln166_fu_259_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_m = 7'd0;
    end else begin
        ap_sig_allocacmp_m = m_2_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        h1_V_ce0 = 1'b1;
    end else begin
        h1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL2w2_0_ce0 = 1'b1;
    end else begin
        p_ZL2w2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL2w2_1_ce0 = 1'b1;
    end else begin
        p_ZL2w2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL2w2_2_ce0 = 1'b1;
    end else begin
        p_ZL2w2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL2w2_3_ce0 = 1'b1;
    end else begin
        p_ZL2w2_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL2w2_4_ce0 = 1'b1;
    end else begin
        p_ZL2w2_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL2w2_5_ce0 = 1'b1;
    end else begin
        p_ZL2w2_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL2w2_6_ce0 = 1'b1;
    end else begin
        p_ZL2w2_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL2w2_7_ce0 = 1'b1;
    end else begin
        p_ZL2w2_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln166_reg_443_pp0_iter1_reg == 1'd1))) begin
        sum_V_16_out_ap_vld = 1'b1;
    end else begin
        sum_V_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln166_fu_265_p2 = (ap_sig_allocacmp_m + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign h1_V_address0 = zext_ln166_fu_271_p1;

assign icmp_ln166_fu_259_p2 = ((ap_sig_allocacmp_m == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_280_p2 = (($signed(zext_ln166_1_fu_276_p1) < $signed(h1_size)) ? 1'b1 : 1'b0);

assign lhs_2_fu_389_p3 = {{lhs_fu_86}, {16'd0}};

assign lshr_ln837_1_fu_286_p4 = {{ap_sig_allocacmp_m[5:3]}};

assign p_ZL2w2_0_address0 = zext_ln837_fu_316_p1;

assign p_ZL2w2_1_address0 = zext_ln837_fu_316_p1;

assign p_ZL2w2_2_address0 = zext_ln837_fu_316_p1;

assign p_ZL2w2_3_address0 = zext_ln837_fu_316_p1;

assign p_ZL2w2_4_address0 = zext_ln837_fu_316_p1;

assign p_ZL2w2_5_address0 = zext_ln837_fu_316_p1;

assign p_ZL2w2_6_address0 = zext_ln837_fu_316_p1;

assign p_ZL2w2_7_address0 = zext_ln837_fu_316_p1;

assign r_V_fu_358_p3 = {{tmp_7_reg_502}, {8'd0}};

assign ret_V_fu_397_p2 = (lhs_2_fu_389_p3 + r_V_2_reg_512);

assign sext_ln164_cast_fu_242_p1 = $signed(sext_ln164);

assign shl_ln838_3_fu_365_p3 = {{h1_V_load_reg_507}, {8'd0}};

assign sum_V_16_out = lhs_fu_86;

assign sum_V_2_fu_412_p3 = ((icmp_ln168_reg_447_pp0_iter2_reg[0:0] == 1'b1) ? sum_V_fu_402_p4 : lhs_fu_86);

assign sum_V_fu_402_p4 = {{ret_V_fu_397_p2[47:16]}};

assign tmp_6_cast_fu_296_p4 = {{n_5[5:3]}};

assign tmp_8_fu_306_p4 = {{{tmp_6_cast_fu_296_p4}, {trunc_ln837}}, {lshr_ln837_1_fu_286_p4}};

assign trunc_ln837_1_fu_328_p1 = ap_sig_allocacmp_m[2:0];

assign zext_ln166_1_fu_276_p1 = ap_sig_allocacmp_m;

assign zext_ln166_fu_271_p1 = ap_sig_allocacmp_m;

assign zext_ln837_fu_316_p1 = tmp_8_fu_306_p4;

endmodule //mlp_accel_mlp_accel_Pipeline_L2_DOT
